apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://github.com/kubernetes/ingress-nginx
  targetNamespace: ingress-nginx